### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by 3ggs**

### CODE REVIEW

**Comment by Bak0n** [comment]
### great job billy back at it again with that vendor prefixing commands which were standard since 2008  👏👏

**Comment by 3ggs** [comment]
btw your website is overflowing both x and y, also what about the motoof and other thingies

**Comment by 3ggs** [comment]
also umm can you fix my anchor tag for the homepage cause lookin at it now its going to someonekill.me/billy/someonekill.me so yay

**Comment by 3ggs** [comment]
# 

> [`_**what is up my doof**_`](

- 

- [ ] 1. url

)

**Comment by 3ggs** [comment]
we should set up something so that every two days to a week our websites automatically update through the github repo

**Pull request merged**
